# Gamma usage example

Counting vector (theta) dynamics makes use of the gamma vector. This example shows how the
function is used.

First, import functions from EV utilities library


In [17]:
from res.EV_utilities import *


Now, define the nodes sequence to be followed

In [ ]:
% nodes sequence
S1 = [0,4,2,5,6,0]
S2 = [0,1,3,5,0]

# append in one big list
S = [S1,S2]

It is necessary to count on with service and charging times to create the X1 state vector
for each vehicle

In [ ]:
# Charging/service times for each node
times = [0.0, 1.1, 0.8, 1.4, 0.4, 1.2, 0.9]

# X1 state
X1 = [[0.0,1.0,2.0,3.0,4.5],
      [0.0,1.1,2.2,3.8,4.5]]

Now, create the counter

In [ ]:


# Tiempo global
k0 = list(range(0,2*(len(X1[0])+len(X2[0]))))
print(k0)

In [19]:
# Matriz con eventos en cada nodo para cada vehículo
aX = []
for i in range(0,nVehicles):
    x = []
    for j in range(0,len(S[i])):
        # agregar ts, nodo, tipo, vehiculo
        x.append([X[i][0][j], S[i][j], 1, i])
        x.append([X[i][1][j], S[i][j], -1, i])
    aX.append(x)
    
print(aX)

[[[0.0, 0, 1, 0], [0.0, 0, -1, 0], [1.0, 4, 1, 0], [1.1, 4, -1, 0], [2.0, 2, 1, 0], [2.2, 2, -1, 0], [3.0, 5, 1, 0], [3.8, 5, -1, 0], [4.5, 0, 1, 0], [4.5, 0, -1, 0]], [[1.0, 0, 1, 1], [1.0, 0, -1, 1], [2.0, 1, 1, 1], [2.1, 1, -1, 1], [2.5, 3, 1, 1], [3.0, 3, -1, 1], [3.2, 5, 1, 1], [3.9, 5, -1, 1], [4.2, 0, 1, 1], [4.2, 0, -1, 1]]]


In [20]:
# Ordenar
oX = []
for i in k0:
    c = float("inf")
    v = 0
    for j in range(0,nVehicles):
        if not aX[j]:
            pass
        elif aX[j][0][0] < c:
            c = aX[j][0][0]
            v = j
    popEvent = aX[v].pop(0) # notice that aX will be empty after this. rerun to obtain new results
    oX.append(popEvent)

print(oX)

[[0.0, 0, 1, 0], [0.0, 0, -1, 0], [1.0, 4, 1, 0], [1.0, 0, 1, 1], [1.0, 0, -1, 1], [1.1, 4, -1, 0], [2.0, 2, 1, 0], [2.0, 1, 1, 1], [2.1, 1, -1, 1], [2.2, 2, -1, 0], [2.5, 3, 1, 1], [3.0, 5, 1, 0], [3.0, 3, -1, 1], [3.2, 5, 1, 1], [3.8, 5, -1, 0], [3.9, 5, -1, 1], [4.2, 0, 1, 1], [4.2, 0, -1, 1], [4.5, 0, 1, 0], [4.5, 0, -1, 0]]


In [21]:
# Prueba de gamma
g, typ = gamma(oX, 1, nNodes)
print(g)

[[-1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [22]:
# Vehiculos en cada nodo
theta = np.zeros((nNodes,1))
#theta[0] = nVehicles
for k in k0:
    g, typ = gamma(oX, k, nNodes)
    theta = theta + g
    print("theta(",k,")= \n",theta,"\n")
    #time.sleep(1)

theta( 0 )= 
 [[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 1 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 2 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]] 

theta( 3 )= 
 [[1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]] 

theta( 4 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]] 

theta( 5 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 6 )= 
 [[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]] 

theta( 7 )= 
 [[0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]] 

theta( 8 )= 
 [[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]] 

theta( 9 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 10 )= 
 [[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]] 

theta( 11 )= 
 [[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]] 

theta( 12 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]] 

theta( 13 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [2.]] 

theta( 14 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]] 

theta( 15 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 16 )= 
 [[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 17 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 18 )= 
 [[1.]
 [0.]
 [0.]
 [0.]