In [1]:
# Required to include project's folder
import sys
sys.path.append('../')

import numpy as np

from res.gamma import gamma


In [2]:
# 2 vehicles
nVehicles = 2
nCustomers = 5

nNodes = nCustomers + 1 # nodos a recorrer y deposito

S1 = [0,4,2,5,0]
S2 = [0,1,3,5,0]

X1 = [[0.0,1.0,2.0,3.0,4.5],[0.0,1.1,2.2,3.8,4.5]]
X2 = [[1.0,2.0,2.5,3.2,4.2],[1.0,2.1,3.0,3.9,4.2]]

S = [S1,S2]
X = [X1,X2]

# Tiempo global
k0 = list(range(0,2*(len(X1[0])+len(X2[0]))))
print(k0)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [3]:
# Matriz con eventos en cada nodo para cada vehículo
aX = []
for i in range(0,nVehicles):
    x = []
    for j in range(0,len(S[i])):
        # agregar ts, nodo, tipo, vehiculo
        x.append([X[i][0][j], S[i][j], 1, i])
        x.append([X[i][1][j], S[i][j], -1, i])
    aX.append(x)
    
print(aX)

[[[0.0, 0, 1, 0], [0.0, 0, -1, 0], [1.0, 4, 1, 0], [1.1, 4, -1, 0], [2.0, 2, 1, 0], [2.2, 2, -1, 0], [3.0, 5, 1, 0], [3.8, 5, -1, 0], [4.5, 0, 1, 0], [4.5, 0, -1, 0]], [[1.0, 0, 1, 1], [1.0, 0, -1, 1], [2.0, 1, 1, 1], [2.1, 1, -1, 1], [2.5, 3, 1, 1], [3.0, 3, -1, 1], [3.2, 5, 1, 1], [3.9, 5, -1, 1], [4.2, 0, 1, 1], [4.2, 0, -1, 1]]]


In [4]:
# Ordenar
oX = []
for i in k0:
    c = float("inf")
    v = 0
    for j in range(0,nVehicles):
        if not aX[j]:
            pass
        elif aX[j][0][0] < c:
            c = aX[j][0][0]
            v = j
    popEvent = aX[v].pop(0) # notice that aX will be empty after this. rerun to obtain new results
    oX.append(popEvent)

print(oX)

[[0.0, 0, 1, 0], [0.0, 0, -1, 0], [1.0, 4, 1, 0], [1.0, 0, 1, 1], [1.0, 0, -1, 1], [1.1, 4, -1, 0], [2.0, 2, 1, 0], [2.0, 1, 1, 1], [2.1, 1, -1, 1], [2.2, 2, -1, 0], [2.5, 3, 1, 1], [3.0, 5, 1, 0], [3.0, 3, -1, 1], [3.2, 5, 1, 1], [3.8, 5, -1, 0], [3.9, 5, -1, 1], [4.2, 0, 1, 1], [4.2, 0, -1, 1], [4.5, 0, 1, 0], [4.5, 0, -1, 0]]


In [5]:
# Prueba de gamma
g, typ = gamma(oX, 1, nNodes)
print(g)

[[-1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [6]:
# Vehiculos en cada nodo
theta = np.zeros((nNodes,1))
#theta[0] = nVehicles
for k in k0:
    g, typ = gamma(oX, k, nNodes)
    theta = theta + g
    print("theta(",k,")= \n",theta,"\n")
    #time.sleep(1)


theta( 0 )= 
 [[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 1 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 2 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]] 

theta( 3 )= 
 [[1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]] 

theta( 4 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]] 

theta( 5 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 6 )= 
 [[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]] 

theta( 7 )= 
 [[0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]] 

theta( 8 )= 
 [[0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]] 

theta( 9 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 10 )= 
 [[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]] 

theta( 11 )= 
 [[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]] 

theta( 12 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]] 

theta( 13 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [2.]] 

theta( 14 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]] 

theta( 15 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 16 )= 
 [[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 17 )= 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]] 

theta( 18 )= 
 [[1.]
 [0.]
 [0.]
 [0.]